### ISSUE TITLE
Add support to name nmdm pairs

### ISSUE THREAD

**Issue by pkgdemon** [araujobsd/vm-bhyve#1]
It would be useful if we could predictably create nmdm pairs by name of the vm-bhyve vm like:

```
/dev/nmdm-${VM}-0a
/dev/nmdm-${VM}-0b
```

Just adding this after our discussion about race condition issues as a possible workaround.

**Comment by pkgdemon** [comment]
Moving this to ixautomation repo.  I think my brain was scattered when I wanted to add it here.  :)

**Comment by araujobsd** [comment]
Here is the right place.

**Comment by araujobsd** [comment]
Committed at: f1d311dcad16c54876a13f02ab87b5fd71633dd2
